language: java
branches:
  only:
  - master
jdk:
  - oraclejdk8
git:
  depth: 1
notifications:
    slack: netstatx:33tG7o9JMAbpyvn4VQVPDiSE
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
 - grep -lr 'maven { url "http://maven.aliyun.com/nexus/content/groups/public" }'|xargs sed -i 's/maven { url "http:\/\/maven.aliyun.com\/nexus\/content\/groups\/public" }//g'
